
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  namespace: default
  labels:
    app: argo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
      - name: argo-app
        image: northamerica-northeast2-docker.pkg.dev/GOOGLE_CLOUD_PROJECT/argo-repo/argo-app:COMMIT_SHA
        ports:
        - containerPort: 8080